[workspace]
resolver = "3"
members = [
    "vulkan-headers",
    "vulkan-headers-generator",
    "vulkan-registry",
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
quick-xml = "0.38.4"
vulkan-registry.path = "vulkan-registry"
